version: 1.2
workflows:
  - name: merge_VCFs
    subclass: WDL
    description: Merge individual sample VCFs to generate a single multi-sample VCF using bcftools
    primaryDescriptorPath: /workflow.wdl
    authors:
      - name: Shloka Negi
        email: shnegi@ucsc.edu
